# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - '3000:3000'
#   mysql-container:
#     image: mysql
#     ports:
#       - '3306:3306'
#     volumes:
#       - /Users/guang/mysql-data:/var/lib/mysql
#   redis-container:
#     image: redis
#     ports:
#       - '6379:6379'
#     volumes:
#       - /Users/guang/aaa:/data
version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
  mysql-container:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - E:\docker_data\mysql\data:/var/lib/mysql
  redis-container:
    image: redis:7.0.13-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - D:\Docker\redis\data2:/data
    command: redis-server --bind 0.0.0.0