# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - '3000:3000'
#   mysql-container:
#     image: mysql
#     ports:
#       - '3306:3306'
#     volumes:
#       - /Users/guang/mysql-data:/var/lib/mysql
#   redis-container:
#     image: redis
#     ports:
#       - '6379:6379'
#     volumes:
#       - /Users/guang/aaa:/data
version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - D:\docker\content:/usr/share/nginx/html
    restart: always
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    ports:
      - 3005:3005
    networks:
      - common-network4
  mysql-container:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - D:\docker\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: _Zz2134330
    networks:
      - common-network4
  redis-container:
    image: redis:7.0.13-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - D:\docker\redis\data2:/data
    networks:
      - common-network4
networks:
  common-network4:
    driver: bridge
